package org.szanto.vaadin_example.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;

public class MainForm extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private TabSheet tabSheet_1;

	@AutoGenerated
	private StockPriceForm stockPriceForm_1;

	@AutoGenerated
	private ParentForm parentForm_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 3981529657079359129L;
	
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// parentForm_1
		parentForm_1 = new ParentForm();
		parentForm_1.setImmediate(false);
		parentForm_1.setWidth("100.0%");
		parentForm_1.setHeight("100.0%");
		tabSheet_1.addTab(parentForm_1, "Parents", null);
		
		// stockPriceForm_1
		stockPriceForm_1 = new StockPriceForm();
		stockPriceForm_1.setImmediate(false);
		stockPriceForm_1.setWidth("100.0%");
		stockPriceForm_1.setHeight("100.0%");
		tabSheet_1.addTab(stockPriceForm_1, "Stock", null);
		
		return tabSheet_1;
	}

}
